import { distance } from './distance';
import { fairness } from './fairness';
import { flexibilityOffered } from './flexibilityOffered';
import { manualBoost } from './manualBoost';
import { peopleServed } from './peopleServed';
import { publicTransport } from './publicTransport';
import { rideType } from './rideType';
import { submissionTime } from './submissionTime';
import type { Rule } from './types';
export declare const ruleRegistry: {
    readonly rideType: Rule<import("./rideType").RideTypeParams>;
    readonly distance: Rule<import("./distance").DistanceParams>;
    readonly publicTransport: Rule<import("./publicTransport").PublicTransportParams>;
    readonly peopleServed: Rule<import("./peopleServed").PeopleServedParams>;
    readonly fairness: Rule<import("./fairness").FairnessParams>;
    readonly submissionTime: Rule<import("./submissionTime").SubmissionTimeParams>;
    readonly flexibilityOffered: Rule<import("./flexibilityOffered").FlexibilityOfferedParams>;
    readonly manualBoost: Rule<import("./manualBoost").ManualBoostParams>;
};
export type RuleType = keyof typeof ruleRegistry;
export type { Rule, RuleContext } from './types';
export { distance, fairness, flexibilityOffered, manualBoost, peopleServed, publicTransport, rideType, submissionTime };
