// GENERATED by scripts/bundle-solver.mjs from src/solver — do not hand-edit (CLAUDE.md hard rule 8).
// Regenerate with `npm run functions:bundle` after any change under src/solver.
import { sortUnits } from './greedy';
import type { SolverInput, SolverOutput } from './types';
export * from './types';
export { fits, dominates, slack, sum, luggageFits, chauffeurLoad } from './seatFit';
export { ruleRegistry, type RuleType } from './rules/index';
export { matchFreedSlot, tryAutoApprove } from './live';
export { CarTimeline, buildTimelines } from './timeline';
export type { NormalizedRequest, NormalizedLeg } from './slots';
export declare function solve(input: SolverInput): SolverOutput;
export { sortUnits };
