#!/usr/bin/env node
// Generates supabase/schema-current.sql — a schema-only, GENERATED, committed
// dump of the `public` schema (tables, views, functions, triggers, policies,
// grants) from the local Supabase stack. Key functions get redefined many
// times across 170+ migrations (e.g. `submit_request`, `v_board_rides`); this
// file lets a developer read the *current* definition of anything without
// replaying every migration (docs/TODO.md "Code review 2026-09-24" R10).
//
// Deterministic: `supabase db dump --local --schema public` (pg_dump under the
// hood) emits no timestamps or version headers, so two consecutive runs
// against the same schema are byte-identical (verified 2026-09-24) — no
// post-processing is needed beyond the header comment this script adds.
//
// Prerequisite: a local Supabase stack with all migrations + seed applied
// (`npm run db:start` then `npm run db:reset`, or CI's "Start local Supabase"
// step). This script does not start/reset the stack itself.
//
// Never touches ../commucar-share.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(repoRoot, "supabase", "schema-current.sql");

const HEADER = `-- GENERATED by \`npm run db:schema\` — do not edit.
-- Schema-only dump of the \`public\` schema (tables, views, functions,
-- triggers, policies, grants) from the local Supabase stack, regenerated
-- after \`supabase db reset\` replays all migrations + seed.sql. Read this to
-- see the *current* definition of any table/function/policy without
-- replaying 170+ migrations one at a time. It is not a migration and is
-- never applied — the migrations under supabase/migrations/ remain the only
-- source of schema history.
-- Convention: a migration that changes a function writes the full
-- \`create or replace function ...\` body (never a partial patch), so this
-- file's function bodies always match a real migration's text.
`;

function main() {
  const tmpDir = mkdtempSync(path.join(tmpdir(), "db-schema-"));
  const tmpFile = path.join(tmpDir, "schema.sql");
  try {
    console.log(`Running: npx supabase db dump --local --schema public -f ${tmpFile}`);
    execFileSync(
      "npx",
      ["supabase", "db", "dump", "--local", "--schema", "public", "-f", tmpFile],
      { stdio: "inherit" },
    );

    const raw = readFileSync(tmpFile, "utf8");
    const body = raw.replace(/\s+$/, "\n");
    writeFileSync(outFile, HEADER + "\n" + body);
    console.log(`Wrote ${path.relative(repoRoot, outFile)}`);
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

try {
  main();
} catch (err) {
  console.error(`db-schema: ${err.message}`);
  process.exitCode = 1;
}
