-- REQ §13.110 (b): the entered times reach the readers. v_my_requests (edit form reopen, /my cards) and
-- v_request_template_suggestions (prefill; the template's time of day anchored to the suggestion's week the
-- same way depart_at/return_at are) gain depart_anchor, arrive_by, return_anchor, leave_dest_at at the END
-- (create or replace view appends only). Bodies copied whole from 20261005180200_stops_active_views.sql
-- (current in schema-current.sql); security_invoker kept, so requests RLS still decides what a reader sees.

create or replace VIEW "public"."v_my_requests" WITH ("security_invoker"='true') AS
 SELECT "request_id",
    "requester_id",
    "department_id",
    "week_start",
    "status",
    "status_reason",
    "is_late",
    "changed_since_solve",
    "depart_at",
    "return_at",
    "trip_shape",
    "one_way_car_mode",
    "needs_car_at_destination",
    "destination",
    "ride_type_name",
    "ride_id",
    "starts_at",
    "ends_at",
    "ride_status",
    "car_name",
    "license_plate",
    "ride_origin",
    "ride_destination",
    "driver_name",
    "role",
    "leg",
    "car_mode",
    "pending_proposal_id",
    "pending_proposal_type",
    "pending_proposal_reason",
    "pending_proposal_expires_at",
    "preferred_car_id",
    "original_depart_at",
    "original_return_at",
    "needs_driver",
    "turnaround_override_minutes",
    "ride_description",
    "guest_passenger_names",
    "companions",
    "child_names",
    "series_id",
    "series_index",
    "series_count",
    "origin_id",
    "origin_text",
    "origin_name",
    "trip_type",
    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('leg', "e"."leg", 'position', "e"."position", 'place_id', "e"."place_id", 'place_text', "e"."place_text", 'name', COALESCE("d"."name", "e"."place_text"), 'eta', "e"."eta", 'active', "e"."active") ORDER BY "e"."leg", "e"."position") AS "jsonb_agg"
           FROM ("public"."request_stops_with_eta"("existing"."request_id") "e"("leg", "position", "place_id", "place_text", "eta", "active")
             LEFT JOIN "public"."destinations" "d" ON (("d"."id" = "e"."place_id")))), '[]'::"jsonb") AS "stops",
    ( SELECT "k"."kept_return_at"
           FROM "public"."requests" "k"
          WHERE ("k"."id" = "existing"."request_id")) AS "kept_return_at",
    ( SELECT "k"."depart_anchor" FROM "public"."requests" "k" WHERE ("k"."id" = "existing"."request_id")) AS "depart_anchor",
    ( SELECT "k"."arrive_by" FROM "public"."requests" "k" WHERE ("k"."id" = "existing"."request_id")) AS "arrive_by",
    ( SELECT "k"."return_anchor" FROM "public"."requests" "k" WHERE ("k"."id" = "existing"."request_id")) AS "return_anchor",
    ( SELECT "k"."leave_dest_at" FROM "public"."requests" "k" WHERE ("k"."id" = "existing"."request_id")) AS "leave_dest_at"
   FROM ( SELECT "existing_1"."request_id",
            "existing_1"."requester_id",
            "existing_1"."department_id",
            "existing_1"."week_start",
            "existing_1"."status",
            "existing_1"."status_reason",
            "existing_1"."is_late",
            "existing_1"."changed_since_solve",
            "existing_1"."depart_at",
            "existing_1"."return_at",
            "existing_1"."trip_shape",
            "existing_1"."one_way_car_mode",
            "existing_1"."needs_car_at_destination",
            "existing_1"."destination",
            "existing_1"."ride_type_name",
            "existing_1"."ride_id",
            "existing_1"."starts_at",
            "existing_1"."ends_at",
            "existing_1"."ride_status",
            "existing_1"."car_name",
            "existing_1"."license_plate",
            "existing_1"."ride_origin",
            "existing_1"."ride_destination",
            "existing_1"."driver_name",
            "existing_1"."role",
            "existing_1"."leg",
            "existing_1"."car_mode",
            "existing_1"."pending_proposal_id",
            "existing_1"."pending_proposal_type",
            "existing_1"."pending_proposal_reason",
            "existing_1"."pending_proposal_expires_at",
            "existing_1"."preferred_car_id",
            "existing_1"."original_depart_at",
            "existing_1"."original_return_at",
            "existing_1"."needs_driver",
            "existing_1"."turnaround_override_minutes",
            "existing_1"."ride_description",
            "existing_1"."guest_passenger_names",
            "existing_1"."companions",
            "existing_1"."child_names",
            "existing_1"."series_id",
            "existing_1"."series_index",
            "existing_1"."series_count",
            "q"."origin_id",
            "q"."origin_text",
            COALESCE("od"."name", "q"."origin_text") AS "origin_name",
            "q"."trip_type"
           FROM ((( SELECT "existing_1_1"."request_id",
                    "existing_1_1"."requester_id",
                    "existing_1_1"."department_id",
                    "existing_1_1"."week_start",
                    "existing_1_1"."status",
                    "existing_1_1"."status_reason",
                    "existing_1_1"."is_late",
                    "existing_1_1"."changed_since_solve",
                    "existing_1_1"."depart_at",
                    "existing_1_1"."return_at",
                    "existing_1_1"."trip_shape",
                    "existing_1_1"."one_way_car_mode",
                    "existing_1_1"."needs_car_at_destination",
                    "existing_1_1"."destination",
                    "existing_1_1"."ride_type_name",
                    "existing_1_1"."ride_id",
                    "existing_1_1"."starts_at",
                    "existing_1_1"."ends_at",
                    "existing_1_1"."ride_status",
                    "existing_1_1"."car_name",
                    "existing_1_1"."license_plate",
                    "existing_1_1"."ride_origin",
                    "existing_1_1"."ride_destination",
                    "existing_1_1"."driver_name",
                    "existing_1_1"."role",
                    "existing_1_1"."leg",
                    "existing_1_1"."car_mode",
                    "existing_1_1"."pending_proposal_id",
                    "existing_1_1"."pending_proposal_type",
                    "existing_1_1"."pending_proposal_reason",
                    "existing_1_1"."pending_proposal_expires_at",
                    "existing_1_1"."preferred_car_id",
                    "existing_1_1"."original_depart_at",
                    "existing_1_1"."original_return_at",
                    "existing_1_1"."needs_driver",
                    "existing_1_1"."turnaround_override_minutes",
                    "existing_1_1"."ride_description",
                    "existing_1_1"."guest_passenger_names",
                    "existing_1_1"."companions",
                    "existing_1_1"."child_names",
                    "q_1"."series_id",
                    "q_1"."series_index",
                    "q_1"."series_count"
                   FROM (( SELECT "existing_1_1_1"."request_id",
                            "existing_1_1_1"."requester_id",
                            "existing_1_1_1"."department_id",
                            "existing_1_1_1"."week_start",
                            "existing_1_1_1"."status",
                            "existing_1_1_1"."status_reason",
                            "existing_1_1_1"."is_late",
                            "existing_1_1_1"."changed_since_solve",
                            "existing_1_1_1"."depart_at",
                            "existing_1_1_1"."return_at",
                            "existing_1_1_1"."trip_shape",
                            "existing_1_1_1"."one_way_car_mode",
                            "existing_1_1_1"."needs_car_at_destination",
                            "existing_1_1_1"."destination",
                            "existing_1_1_1"."ride_type_name",
                            "existing_1_1_1"."ride_id",
                            "existing_1_1_1"."starts_at",
                            "existing_1_1_1"."ends_at",
                            "existing_1_1_1"."ride_status",
                            "existing_1_1_1"."car_name",
                            "existing_1_1_1"."license_plate",
                            "existing_1_1_1"."ride_origin",
                            "existing_1_1_1"."ride_destination",
                            "existing_1_1_1"."driver_name",
                            "existing_1_1_1"."role",
                            "existing_1_1_1"."leg",
                            "existing_1_1_1"."car_mode",
                            "existing_1_1_1"."pending_proposal_id",
                            "existing_1_1_1"."pending_proposal_type",
                            "existing_1_1_1"."pending_proposal_reason",
                            "existing_1_1_1"."pending_proposal_expires_at",
                            "existing_1_1_1"."preferred_car_id",
                            "existing_1_1_1"."original_depart_at",
                            "existing_1_1_1"."original_return_at",
                            "existing_1_1_1"."needs_driver",
                            "existing_1_1_1"."turnaround_override_minutes",
                            "existing_1_1_1"."ride_description",
                            "existing_1_1_1"."guest_passenger_names",
                            "existing_1_1_1"."companions",
                            COALESCE(( SELECT "array_agg"("c"."full_name" ORDER BY "c"."full_name") AS "array_agg"
                                   FROM ("public"."request_children" "rc"
                                     JOIN "public"."children" "c" ON (("c"."id" = "rc"."child_id")))
                                  WHERE ("rc"."request_id" = "existing_1_1_1"."request_id")), '{}'::"text"[]) AS "child_names"
                           FROM ( SELECT "existing_1_1_1_1"."request_id",
                                    "existing_1_1_1_1"."requester_id",
                                    "existing_1_1_1_1"."department_id",
                                    "existing_1_1_1_1"."week_start",
                                    "existing_1_1_1_1"."status",
                                    "existing_1_1_1_1"."status_reason",
                                    "existing_1_1_1_1"."is_late",
                                    "existing_1_1_1_1"."changed_since_solve",
                                    "existing_1_1_1_1"."depart_at",
                                    "existing_1_1_1_1"."return_at",
                                    "existing_1_1_1_1"."trip_shape",
                                    "existing_1_1_1_1"."one_way_car_mode",
                                    "existing_1_1_1_1"."needs_car_at_destination",
                                    "existing_1_1_1_1"."destination",
                                    "existing_1_1_1_1"."ride_type_name",
                                    "existing_1_1_1_1"."ride_id",
                                    "existing_1_1_1_1"."starts_at",
                                    "existing_1_1_1_1"."ends_at",
                                    "existing_1_1_1_1"."ride_status",
                                    "existing_1_1_1_1"."car_name",
                                    "existing_1_1_1_1"."license_plate",
                                    "existing_1_1_1_1"."ride_origin",
                                    "existing_1_1_1_1"."ride_destination",
                                    "existing_1_1_1_1"."driver_name",
                                    "existing_1_1_1_1"."role",
                                    "existing_1_1_1_1"."leg",
                                    "existing_1_1_1_1"."car_mode",
                                    "existing_1_1_1_1"."pending_proposal_id",
                                    "existing_1_1_1_1"."pending_proposal_type",
                                    "existing_1_1_1_1"."pending_proposal_reason",
                                    "existing_1_1_1_1"."pending_proposal_expires_at",
                                    "existing_1_1_1_1"."preferred_car_id",
                                    "existing_1_1_1_1"."original_depart_at",
                                    "existing_1_1_1_1"."original_return_at",
                                    "existing_1_1_1_1"."needs_driver",
                                    "existing_1_1_1_1"."turnaround_override_minutes",
                                    "q_1_1"."ride_description",
                                    "q_1_1"."guest_passenger_names",
                                    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('profile_id', "p"."id", 'name', "p"."full_name") ORDER BY "p"."full_name", "p"."id") AS "jsonb_agg"
   FROM ("public"."request_companions" "rc"
     JOIN "public"."profiles" "p" ON (("p"."id" = "rc"."profile_id")))
  WHERE ("rc"."request_id" = "q_1_1"."id")), '[]'::"jsonb") AS "companions"
                                   FROM (( SELECT "existing_1_1_1_1_1"."request_id",
    "existing_1_1_1_1_1"."requester_id",
    "existing_1_1_1_1_1"."department_id",
    "existing_1_1_1_1_1"."week_start",
    "existing_1_1_1_1_1"."status",
    "existing_1_1_1_1_1"."status_reason",
    "existing_1_1_1_1_1"."is_late",
    "existing_1_1_1_1_1"."changed_since_solve",
    "existing_1_1_1_1_1"."depart_at",
    "existing_1_1_1_1_1"."return_at",
    "existing_1_1_1_1_1"."trip_shape",
    "existing_1_1_1_1_1"."one_way_car_mode",
    "existing_1_1_1_1_1"."needs_car_at_destination",
    "existing_1_1_1_1_1"."destination",
    "existing_1_1_1_1_1"."ride_type_name",
    "existing_1_1_1_1_1"."ride_id",
    "existing_1_1_1_1_1"."starts_at",
    "existing_1_1_1_1_1"."ends_at",
    "existing_1_1_1_1_1"."ride_status",
    "existing_1_1_1_1_1"."car_name",
    "existing_1_1_1_1_1"."license_plate",
    "existing_1_1_1_1_1"."ride_origin",
    "existing_1_1_1_1_1"."ride_destination",
    "existing_1_1_1_1_1"."driver_name",
    "existing_1_1_1_1_1"."role",
    "existing_1_1_1_1_1"."leg",
    "existing_1_1_1_1_1"."car_mode",
    "existing_1_1_1_1_1"."pending_proposal_id",
    "existing_1_1_1_1_1"."pending_proposal_type",
    "existing_1_1_1_1_1"."pending_proposal_reason",
    "existing_1_1_1_1_1"."pending_proposal_expires_at",
    "q_1_1_1"."preferred_car_id",
    "q_1_1_1"."original_depart_at",
    "q_1_1_1"."original_return_at",
    "r"."needs_driver",
    "r"."turnaround_override_minutes"
   FROM ((( SELECT "q_1_1_1_1"."id" AS "request_id",
      "q_1_1_1_1"."requester_id",
      "q_1_1_1_1"."department_id",
      "q_1_1_1_1"."week_start",
      "q_1_1_1_1"."status",
      "q_1_1_1_1"."status_reason",
      "q_1_1_1_1"."is_late",
      "q_1_1_1_1"."changed_since_solve",
      "q_1_1_1_1"."depart_at",
      "q_1_1_1_1"."return_at",
      "q_1_1_1_1"."trip_shape",
      "q_1_1_1_1"."one_way_car_mode",
      "q_1_1_1_1"."needs_car_at_destination",
      COALESCE("dst"."name", "q_1_1_1_1"."destination_text") AS "destination",
      "rt"."name_he" AS "ride_type_name",
      "r_1"."id" AS "ride_id",
      "r_1"."starts_at",
      "r_1"."ends_at",
      "r_1"."status" AS "ride_status",
      "c"."name" AS "car_name",
      "c"."license_plate",
      "ro"."name" AS "ride_origin",
      "re"."name" AS "ride_destination",
      "drv"."full_name" AS "driver_name",
      "rr"."role",
      "rr"."leg",
      "rr"."car_mode",
      "pr"."id" AS "pending_proposal_id",
      "pr"."type" AS "pending_proposal_type",
      "pr"."reason_he" AS "pending_proposal_reason",
      "pr"."expires_at" AS "pending_proposal_expires_at"
     FROM ((((((((("public"."requests" "q_1_1_1_1"
       JOIN "public"."ride_types" "rt" ON (("rt"."id" = "q_1_1_1_1"."ride_type_id")))
       LEFT JOIN "public"."destinations" "dst" ON (("dst"."id" = "q_1_1_1_1"."destination_id")))
       LEFT JOIN "public"."ride_requests" "rr" ON (("rr"."request_id" = "q_1_1_1_1"."id")))
       LEFT JOIN "public"."rides" "r_1" ON ((("r_1"."id" = "rr"."ride_id") AND ("r_1"."status" <> 'cancelled'::"public"."ride_status"))))
       LEFT JOIN "public"."destinations" "ro" ON (("ro"."id" = "r_1"."origin_id")))
       LEFT JOIN "public"."destinations" "re" ON (("re"."id" = "r_1"."destination_id")))
       LEFT JOIN "public"."cars" "c" ON (("c"."id" = "r_1"."car_id")))
       LEFT JOIN "public"."profiles" "drv" ON (("drv"."id" = "r_1"."driver_id")))
       LEFT JOIN "public"."proposals" "pr" ON ((("pr"."request_id" = "q_1_1_1_1"."id") AND ("pr"."status" = 'sent'::"public"."proposal_status"))))) "existing_1_1_1_1_1"
     JOIN "public"."requests" "q_1_1_1" ON (("q_1_1_1"."id" = "existing_1_1_1_1_1"."request_id")))
     LEFT JOIN "public"."rides" "r" ON (("r"."id" = "existing_1_1_1_1_1"."ride_id")))) "existing_1_1_1_1"
                                     JOIN "public"."requests" "q_1_1" ON (("q_1_1"."id" = "existing_1_1_1_1"."request_id")))) "existing_1_1_1") "existing_1_1"
                     JOIN "public"."requests" "q_1" ON (("q_1"."id" = "existing_1_1"."request_id")))) "existing_1"
             JOIN "public"."requests" "q" ON (("q"."id" = "existing_1"."request_id")))
             LEFT JOIN "public"."destinations" "od" ON (("od"."id" = "q"."origin_id")))) "existing";

create or replace VIEW "public"."v_request_template_suggestions" WITH ("security_invoker"='true') AS
 SELECT "existing"."template_id",
    "existing"."department_id",
    "existing"."week_start",
    "existing"."destination_id",
    "existing"."destination_text",
    "existing"."destination_name",
    "existing"."ride_type_id",
    "existing"."ride_type_name",
    "existing"."trip_shape",
    "existing"."depart_dow",
    "existing"."depart_time",
    "existing"."return_dow",
    "existing"."return_time",
    "existing"."depart_at",
    "existing"."return_at",
    "existing"."one_way_car_mode",
    "existing"."needs_car_at_destination",
    "existing"."adults",
    "existing"."child_seats",
    "existing"."boosters",
    "existing"."child_ids",
    "existing"."companion_ids",
    "existing"."has_luggage",
    "existing"."flex_depart_early",
    "existing"."flex_depart_late",
    "existing"."flex_return_early",
    "existing"."flex_return_late",
    "existing"."preferred_car_id",
    "existing"."ride_description",
    "existing"."guest_passenger_names",
    "existing"."notes",
    "existing"."origin_id",
    "existing"."origin_text",
    "existing"."origin_name",
    "existing"."trip_type",
    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('leg', ("item"."value" ->> 'leg'::"text"), 'position', (("item"."value" ->> 'position'::"text"))::smallint, 'place_id', (NULLIF(("item"."value" ->> 'place_id'::"text"), ''::"text"))::"uuid", 'place_text', ("item"."value" ->> 'place_text'::"text"), 'name', COALESCE("d"."name", ("item"."value" ->> 'place_text'::"text")), 'eta', NULL::"text", 'active', ((("item"."value" ->> 'leg'::"text") = 'out'::"text") OR ("tpl"."return_dow" IS NOT NULL))) ORDER BY ("item"."value" ->> 'leg'::"text"), (("item"."value" ->> 'position'::"text"))::smallint) AS "jsonb_agg"
           FROM ("jsonb_array_elements"("tpl"."stops") "item"("value")
             LEFT JOIN "public"."destinations" "d" ON (("d"."id" = (NULLIF(("item"."value" ->> 'place_id'::"text"), ''::"text"))::"uuid")))), '[]'::"jsonb") AS "stops",
    "tpl"."depart_anchor",
        CASE
            WHEN (("tpl"."arrive_by_time" IS NOT NULL) AND ("tpl"."depart_dow" IS NOT NULL)) THEN (((("existing"."week_start" + ("tpl"."depart_dow")::integer + (CASE WHEN ("tpl"."arrive_by_time" < "tpl"."depart_time") THEN 1 ELSE 0 END)))::timestamp without time zone + ("tpl"."arrive_by_time")::interval) AT TIME ZONE 'Asia/Jerusalem'::"text")
            ELSE NULL::timestamp with time zone
        END AS "arrive_by",
    "tpl"."return_anchor",
        CASE
            WHEN (("tpl"."leave_dest_time" IS NOT NULL) AND ("tpl"."return_dow" IS NOT NULL)) THEN (((("existing"."week_start" + ("tpl"."return_dow")::integer - (CASE WHEN ("tpl"."leave_dest_time" > "tpl"."return_time") THEN 1 ELSE 0 END)))::timestamp without time zone + ("tpl"."leave_dest_time")::interval) AT TIME ZONE 'Asia/Jerusalem'::"text")
            ELSE NULL::timestamp with time zone
        END AS "leave_dest_at"
   FROM (( SELECT "existing_1"."template_id",
            "existing_1"."department_id",
            "existing_1"."week_start",
            "existing_1"."destination_id",
            "existing_1"."destination_text",
            "existing_1"."destination_name",
            "existing_1"."ride_type_id",
            "existing_1"."ride_type_name",
            "existing_1"."trip_shape",
            "existing_1"."depart_dow",
            "existing_1"."depart_time",
            "existing_1"."return_dow",
            "existing_1"."return_time",
            "existing_1"."depart_at",
            "existing_1"."return_at",
            "existing_1"."one_way_car_mode",
            "existing_1"."needs_car_at_destination",
            "existing_1"."adults",
            "existing_1"."child_seats",
            "existing_1"."boosters",
            "existing_1"."child_ids",
            "existing_1"."companion_ids",
            "existing_1"."has_luggage",
            "existing_1"."flex_depart_early",
            "existing_1"."flex_depart_late",
            "existing_1"."flex_return_early",
            "existing_1"."flex_return_late",
            "existing_1"."preferred_car_id",
            "existing_1"."ride_description",
            "existing_1"."guest_passenger_names",
            "existing_1"."notes",
            "t"."origin_id",
            "t"."origin_text",
            COALESCE("od"."name", "t"."origin_text") AS "origin_name",
            "t"."trip_type"
           FROM ((( SELECT "t_1"."id" AS "template_id",
                    "t_1"."department_id",
                    "w"."week_start",
                    "t_1"."destination_id",
                    "t_1"."destination_text",
                    COALESCE("dst"."name", "t_1"."destination_text") AS "destination_name",
                    "t_1"."ride_type_id",
                    "rt"."name_he" AS "ride_type_name",
                    "t_1"."trip_shape",
                    "t_1"."depart_dow",
                    "t_1"."depart_time",
                    "t_1"."return_dow",
                    "t_1"."return_time",
                        CASE
                            WHEN ("t_1"."depart_dow" IS NOT NULL) THEN (((("w"."week_start" + ("t_1"."depart_dow")::integer))::timestamp without time zone + ("t_1"."depart_time")::interval) AT TIME ZONE 'Asia/Jerusalem'::"text")
                            ELSE NULL::timestamp with time zone
                        END AS "depart_at",
                        CASE
                            WHEN ("t_1"."return_dow" IS NOT NULL) THEN (((("w"."week_start" + ("t_1"."return_dow")::integer))::timestamp without time zone + ("t_1"."return_time")::interval) AT TIME ZONE 'Asia/Jerusalem'::"text")
                            ELSE NULL::timestamp with time zone
                        END AS "return_at",
                    "t_1"."one_way_car_mode",
                    "t_1"."needs_car_at_destination",
                    "t_1"."adults",
                    "t_1"."child_seats",
                    "t_1"."boosters",
                    "t_1"."child_ids",
                    "t_1"."companion_ids",
                    "t_1"."has_luggage",
                    "t_1"."flex_depart_early",
                    "t_1"."flex_depart_late",
                    "t_1"."flex_return_early",
                    "t_1"."flex_return_late",
                    "t_1"."preferred_car_id",
                    "t_1"."ride_description",
                    "t_1"."guest_passenger_names",
                    "t_1"."notes"
                   FROM ((("public"."request_templates" "t_1"
                     JOIN "public"."weeks" "w" ON ((("w"."department_id" = "t_1"."department_id") AND ("w"."phase" = 'open'::"public"."week_phase"))))
                     LEFT JOIN "public"."destinations" "dst" ON (("dst"."id" = "t_1"."destination_id")))
                     JOIN "public"."ride_types" "rt" ON (("rt"."id" = "t_1"."ride_type_id")))
                  WHERE (("t_1"."requester_id" = ( SELECT "auth"."uid"() AS "uid")) AND "t_1"."is_active" AND (("t_1"."snoozed_until_week" IS NULL) OR ("t_1"."snoozed_until_week" <= "w"."week_start")) AND (NOT (EXISTS ( SELECT 1
                           FROM "public"."requests" "q"
                          WHERE (("q"."template_id" = "t_1"."id") AND ("q"."week_start" = "w"."week_start") AND ("q"."status" <> ALL (ARRAY['withdrawn'::"public"."request_status", 'cancelled'::"public"."request_status", 'draft'::"public"."request_status"])))))))) "existing_1"
             JOIN "public"."request_templates" "t" ON (("t"."id" = "existing_1"."template_id")))
             LEFT JOIN "public"."destinations" "od" ON (("od"."id" = "t"."origin_id")))) "existing"
     JOIN "public"."request_templates" "tpl" ON (("tpl"."id" = "existing"."template_id")));
