-- REQ §13.93/§13.96 follow-up: a request keeps its last real return time when switched to one-way (requests_return_presence_ck
-- forces return_at null for one_way_to), so switching back restores it.
-- v_my_requests exposes requests.kept_return_at (appended) so the form can prefill the return on edit. Wrap-and-append over the
-- previous definition (20261004160800), untouched.
create or replace view public.v_my_requests with (security_invoker = true) as
select
  existing.*,
  coalesce((
    select jsonb_agg(jsonb_build_object(
        'leg', e.leg, 'position', e."position", 'place_id', e.place_id, 'place_text', e.place_text,
        'name', coalesce(d.name, e.place_text), 'eta', e.eta
      ) order by e.leg, e."position")
    from public.request_stop_etas(existing.request_id) e
    left join public.destinations d on d.id = e.place_id
  ), '[]'::jsonb) as stops,
  (select k.kept_return_at from public.requests k where k.id = existing.request_id) as kept_return_at
from (
 SELECT existing.request_id,
    existing.requester_id,
    existing.department_id,
    existing.week_start,
    existing.status,
    existing.status_reason,
    existing.is_late,
    existing.changed_since_solve,
    existing.depart_at,
    existing.return_at,
    existing.trip_shape,
    existing.one_way_car_mode,
    existing.needs_car_at_destination,
    existing.destination,
    existing.ride_type_name,
    existing.ride_id,
    existing.starts_at,
    existing.ends_at,
    existing.ride_status,
    existing.car_name,
    existing.license_plate,
    existing.ride_origin,
    existing.ride_destination,
    existing.driver_name,
    existing.role,
    existing.leg,
    existing.car_mode,
    existing.pending_proposal_id,
    existing.pending_proposal_type,
    existing.pending_proposal_reason,
    existing.pending_proposal_expires_at,
    existing.preferred_car_id,
    existing.original_depart_at,
    existing.original_return_at,
    existing.needs_driver,
    existing.turnaround_override_minutes,
    existing.ride_description,
    existing.guest_passenger_names,
    existing.companions,
    existing.child_names,
    existing.series_id,
    existing.series_index,
    existing.series_count,
    q.origin_id,
    q.origin_text,
    COALESCE(od.name, q.origin_text) AS origin_name,
    q.trip_type
   FROM ( SELECT existing_1.request_id,
            existing_1.requester_id,
            existing_1.department_id,
            existing_1.week_start,
            existing_1.status,
            existing_1.status_reason,
            existing_1.is_late,
            existing_1.changed_since_solve,
            existing_1.depart_at,
            existing_1.return_at,
            existing_1.trip_shape,
            existing_1.one_way_car_mode,
            existing_1.needs_car_at_destination,
            existing_1.destination,
            existing_1.ride_type_name,
            existing_1.ride_id,
            existing_1.starts_at,
            existing_1.ends_at,
            existing_1.ride_status,
            existing_1.car_name,
            existing_1.license_plate,
            existing_1.ride_origin,
            existing_1.ride_destination,
            existing_1.driver_name,
            existing_1.role,
            existing_1.leg,
            existing_1.car_mode,
            existing_1.pending_proposal_id,
            existing_1.pending_proposal_type,
            existing_1.pending_proposal_reason,
            existing_1.pending_proposal_expires_at,
            existing_1.preferred_car_id,
            existing_1.original_depart_at,
            existing_1.original_return_at,
            existing_1.needs_driver,
            existing_1.turnaround_override_minutes,
            existing_1.ride_description,
            existing_1.guest_passenger_names,
            existing_1.companions,
            existing_1.child_names,
            q_1.series_id,
            q_1.series_index,
            q_1.series_count
           FROM ( SELECT existing_1_1.request_id,
                    existing_1_1.requester_id,
                    existing_1_1.department_id,
                    existing_1_1.week_start,
                    existing_1_1.status,
                    existing_1_1.status_reason,
                    existing_1_1.is_late,
                    existing_1_1.changed_since_solve,
                    existing_1_1.depart_at,
                    existing_1_1.return_at,
                    existing_1_1.trip_shape,
                    existing_1_1.one_way_car_mode,
                    existing_1_1.needs_car_at_destination,
                    existing_1_1.destination,
                    existing_1_1.ride_type_name,
                    existing_1_1.ride_id,
                    existing_1_1.starts_at,
                    existing_1_1.ends_at,
                    existing_1_1.ride_status,
                    existing_1_1.car_name,
                    existing_1_1.license_plate,
                    existing_1_1.ride_origin,
                    existing_1_1.ride_destination,
                    existing_1_1.driver_name,
                    existing_1_1.role,
                    existing_1_1.leg,
                    existing_1_1.car_mode,
                    existing_1_1.pending_proposal_id,
                    existing_1_1.pending_proposal_type,
                    existing_1_1.pending_proposal_reason,
                    existing_1_1.pending_proposal_expires_at,
                    existing_1_1.preferred_car_id,
                    existing_1_1.original_depart_at,
                    existing_1_1.original_return_at,
                    existing_1_1.needs_driver,
                    existing_1_1.turnaround_override_minutes,
                    existing_1_1.ride_description,
                    existing_1_1.guest_passenger_names,
                    existing_1_1.companions,
                    COALESCE(( SELECT array_agg(c.full_name ORDER BY c.full_name) AS array_agg
                           FROM request_children rc
                             JOIN children c ON c.id = rc.child_id
                          WHERE rc.request_id = existing_1_1.request_id), '{}'::text[]) AS child_names
                   FROM ( SELECT existing_1_1_1.request_id,
                            existing_1_1_1.requester_id,
                            existing_1_1_1.department_id,
                            existing_1_1_1.week_start,
                            existing_1_1_1.status,
                            existing_1_1_1.status_reason,
                            existing_1_1_1.is_late,
                            existing_1_1_1.changed_since_solve,
                            existing_1_1_1.depart_at,
                            existing_1_1_1.return_at,
                            existing_1_1_1.trip_shape,
                            existing_1_1_1.one_way_car_mode,
                            existing_1_1_1.needs_car_at_destination,
                            existing_1_1_1.destination,
                            existing_1_1_1.ride_type_name,
                            existing_1_1_1.ride_id,
                            existing_1_1_1.starts_at,
                            existing_1_1_1.ends_at,
                            existing_1_1_1.ride_status,
                            existing_1_1_1.car_name,
                            existing_1_1_1.license_plate,
                            existing_1_1_1.ride_origin,
                            existing_1_1_1.ride_destination,
                            existing_1_1_1.driver_name,
                            existing_1_1_1.role,
                            existing_1_1_1.leg,
                            existing_1_1_1.car_mode,
                            existing_1_1_1.pending_proposal_id,
                            existing_1_1_1.pending_proposal_type,
                            existing_1_1_1.pending_proposal_reason,
                            existing_1_1_1.pending_proposal_expires_at,
                            existing_1_1_1.preferred_car_id,
                            existing_1_1_1.original_depart_at,
                            existing_1_1_1.original_return_at,
                            existing_1_1_1.needs_driver,
                            existing_1_1_1.turnaround_override_minutes,
                            q_1_1.ride_description,
                            q_1_1.guest_passenger_names,
                            COALESCE(( SELECT jsonb_agg(jsonb_build_object('profile_id', p.id, 'name', p.full_name) ORDER BY p.full_name, p.id) AS jsonb_agg
                                   FROM request_companions rc
                                     JOIN profiles p ON p.id = rc.profile_id
                                  WHERE rc.request_id = q_1_1.id), '[]'::jsonb) AS companions
                           FROM ( SELECT existing_1_1_1_1.request_id,
                                    existing_1_1_1_1.requester_id,
                                    existing_1_1_1_1.department_id,
                                    existing_1_1_1_1.week_start,
                                    existing_1_1_1_1.status,
                                    existing_1_1_1_1.status_reason,
                                    existing_1_1_1_1.is_late,
                                    existing_1_1_1_1.changed_since_solve,
                                    existing_1_1_1_1.depart_at,
                                    existing_1_1_1_1.return_at,
                                    existing_1_1_1_1.trip_shape,
                                    existing_1_1_1_1.one_way_car_mode,
                                    existing_1_1_1_1.needs_car_at_destination,
                                    existing_1_1_1_1.destination,
                                    existing_1_1_1_1.ride_type_name,
                                    existing_1_1_1_1.ride_id,
                                    existing_1_1_1_1.starts_at,
                                    existing_1_1_1_1.ends_at,
                                    existing_1_1_1_1.ride_status,
                                    existing_1_1_1_1.car_name,
                                    existing_1_1_1_1.license_plate,
                                    existing_1_1_1_1.ride_origin,
                                    existing_1_1_1_1.ride_destination,
                                    existing_1_1_1_1.driver_name,
                                    existing_1_1_1_1.role,
                                    existing_1_1_1_1.leg,
                                    existing_1_1_1_1.car_mode,
                                    existing_1_1_1_1.pending_proposal_id,
                                    existing_1_1_1_1.pending_proposal_type,
                                    existing_1_1_1_1.pending_proposal_reason,
                                    existing_1_1_1_1.pending_proposal_expires_at,
                                    q_1_1_1.preferred_car_id,
                                    q_1_1_1.original_depart_at,
                                    q_1_1_1.original_return_at,
                                    r.needs_driver,
                                    r.turnaround_override_minutes
                                   FROM ( SELECT q_1_1_1_1.id AS request_id,
    q_1_1_1_1.requester_id,
    q_1_1_1_1.department_id,
    q_1_1_1_1.week_start,
    q_1_1_1_1.status,
    q_1_1_1_1.status_reason,
    q_1_1_1_1.is_late,
    q_1_1_1_1.changed_since_solve,
    q_1_1_1_1.depart_at,
    q_1_1_1_1.return_at,
    q_1_1_1_1.trip_shape,
    q_1_1_1_1.one_way_car_mode,
    q_1_1_1_1.needs_car_at_destination,
    COALESCE(dst.name, q_1_1_1_1.destination_text) AS destination,
    rt.name_he AS ride_type_name,
    r_1.id AS ride_id,
    r_1.starts_at,
    r_1.ends_at,
    r_1.status AS ride_status,
    c.name AS car_name,
    c.license_plate,
    ro.name AS ride_origin,
    re.name AS ride_destination,
    drv.full_name AS driver_name,
    rr.role,
    rr.leg,
    rr.car_mode,
    pr.id AS pending_proposal_id,
    pr.type AS pending_proposal_type,
    pr.reason_he AS pending_proposal_reason,
    pr.expires_at AS pending_proposal_expires_at
   FROM requests q_1_1_1_1
     JOIN ride_types rt ON rt.id = q_1_1_1_1.ride_type_id
     LEFT JOIN destinations dst ON dst.id = q_1_1_1_1.destination_id
     LEFT JOIN ride_requests rr ON rr.request_id = q_1_1_1_1.id
     LEFT JOIN rides r_1 ON r_1.id = rr.ride_id AND r_1.status <> 'cancelled'::ride_status
     LEFT JOIN destinations ro ON ro.id = r_1.origin_id
     LEFT JOIN destinations re ON re.id = r_1.destination_id
     LEFT JOIN cars c ON c.id = r_1.car_id
     LEFT JOIN profiles drv ON drv.id = r_1.driver_id
     LEFT JOIN proposals pr ON pr.request_id = q_1_1_1_1.id AND pr.status = 'sent'::proposal_status) existing_1_1_1_1
                                     JOIN requests q_1_1_1 ON q_1_1_1.id = existing_1_1_1_1.request_id
                                     LEFT JOIN rides r ON r.id = existing_1_1_1_1.ride_id) existing_1_1_1
                             JOIN requests q_1_1 ON q_1_1.id = existing_1_1_1.request_id) existing_1_1) existing_1
             JOIN requests q_1 ON q_1.id = existing_1.request_id) existing
     JOIN requests q ON q.id = existing.request_id
     LEFT JOIN destinations od ON od.id = q.origin_id
) existing;
